fixed error with chaos test changed the test to fail on even number tries
Signed-off-by: Birol Bilgin <birolbilgin@gmail.com>

diff --git a/.github/workflows/lint-workflow.yaml b/.github/workflows/lint-workflow.yaml
--- a/.github/workflows/lint-workflow.yaml
+++ b/.github/workflows/lint-workflow.yaml
@@ -56,11 +56,12 @@ jobs:
           # hard-code the path instead of using ${{ github.repository }} to make sure it works for forked repo as well
           path: src/github.com/testomraade/mergeq
 
-      - name: Validate Someties
+      - name: Fail on First Time
         shell: bash
         run: |
-          num=$RANDOM
+          num=${{ github.run_attempt }}
           # Test if it's divisible by 2
           if (( num % 2 == 0 )); then
-              echo Sorry, $num is divisible by 2. It is time to fail"
+            echo "Sorry, $num is divisible by 2. It is time to fail"
+            exit 1
           fi
